### ISSUE TITLE
Codes for figure 1,3,4, and 5 

### ISSUE THREAD

**Issue by yswang1717** [timgaripov/swa#17]
Hello, 
Could you please give me the codes to plot the figure of preactivations (Fig. 1,3) and L2-R CE train loss(4,5)? The link for the referenced repo would be ok as well.

**Comment by izmailovpavel** [comment]
Hey @yswang1717, check out this issue: https://github.com/timgaripov/swa/issues/5, and this post specifically https://github.com/timgaripov/swa/issues/5#issuecomment-546636630. Let me know if you have any further questions.
