### ISSUE TITLE
Finetuning model with SWA

### ISSUE THREAD

**Issue by mrgloom** [timgaripov/swa#20]
https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch
Can I use SWA to finetune already trained model? 
![image](https://user-images.githubusercontent.com/4003908/97701575-8cdaaf00-1aa5-11eb-8fde-6b389d32a118.png)
![image](https://user-images.githubusercontent.com/4003908/97701591-93692680-1aa5-11eb-8bf4-2c192cc9f39d.png)
Do I need to use only last 25% Average DNN weights section in case of finetuning?

**Comment by izmailovpavel** [comment]
Hey @mrgloom you definitely can. We used SWA to finetune pre-trained PyTorch ImageNet models in the paper. You don't have to do 25% exactly, I would run SWA for as long as you wish to wait, starting from your pre-trained solutions.
