### ISSUE TITLE
How many weights instances stored in memory simultaneously?

### ISSUE THREAD

**Issue by mrgloom** [timgaripov/swa#21]
How many weights instances stored in memory simultaneously?
As I can see it's only 2 instances of weights and n_models is just some parameter? So it's not storing N models in memory during training?
![image](https://user-images.githubusercontent.com/4003908/97716057-0cbf4400-1abb-11eb-93fe-0574174c647c.png)

**Comment by izmailovpavel** [comment]
Hey @mrgloom, that is correct. All we need to store is the current SGD iterate w, and the SWA weights w_SWA.
