### ISSUE TITLE
Incorrect model parameter update?

### ISSUE THREAD

**Issue by hahnicity** [timgaripov/swa#3]
In the code you update SWA weights via

`utils.moving_average(swa_model, model, 1.0 / (swa_n + 1))`

Then in the `moving_average` function your math is implemented

```
def moving_average(net1, net2, alpha=1):
    for param1, param2 in zip(net1.parameters(), net2.parameters()):
        param1.data *= (1.0 - alpha)
        param1.data += param2.data * alpha
```
Is this updating correctly? I'm assuming this part of the code is performing the part in Algorithm 1 from the paper where you "Update average" or updating the stochastic weight average. But the math feels a bit off. Wouldn't the equation look something like

`param1.data = (param1.data * ((1.0 / alpha) - 1) + param2.data) * alpha`

To be more in accordance with the stochastic weight update eq.

**Comment by izmailovpavel** [comment]
So in our version `alpha == 1/(n+1)`. Then `1.0 - alpha == n / (n+1)` and our update is `param1 = param1 * n /(n+1) + param2 / (n+1) == (param1 * n + param2) / (n+1)`. Now your version: `((1/alpha) - 1) == n`, and the update is `param1 = (param1 * n + param2) / (n+1)`. So if my derivations are correct here, the two versions are equivalent.

**Comment by hahnicity** [comment]
Yeah, my bad you're right.
