### ISSUE TITLE
About preresnet results

### ISSUE THREAD

**Issue by BIGBALLON** [timgaripov/swa#4]
Hi, @timgaripov ,@izmailovpavel ,

Thanks for your pretty work & nice paper.

from the issues 
https://github.com/bearpaw/pytorch-classification/issues/6
and https://github.com/bearpaw/pytorch-classification/pull/9

preresnet-110 is **not really** 110 layers, 
because we use bottleneck. ((110-2)/6 =18, 18*9+2=164 layers)

```python
        n = (depth - 2) // 6
        block = Bottleneck if depth >= 44 else BasicBlock
```
the correct way is:

```python
        if depth >= 44:
            assert (depth - 2) % 9 == 0
            n = (depth - 2) // 9
            block = Bottleneck

        else:
            assert (depth - 2) % 6 == 0, 'depth should be 6n+2'
            n = (depth - 2) // 6
            block = BasicBlock
```
so the results of preresnet seems **not correct**,
look forward the new experiments in swa!

thanks a lot!

**Comment by izmailovpavel** [comment]
Thanks for bringing this up! We will change the PreResNet110 -> PreResNet164 in the table and also run experiments with the correct PreResNet110.

**Comment by izmailovpavel** [comment]
We fixed the implementation, and added new results for the actual PreResNet-110. Thanks for bringing this issue up! Now closing the issue.
